databases:
  - name: healthreport
    plan: free
    databaseName: health_report
    user: mysite


services:
  - type: web
    plan: free
    name: health_report
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn health_report.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: health_report
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4