# Generated by Django 5.1.3 on 2024-11-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disease',
            table='disease',
        ),
        migrations.AlterModelTable(
            name='patients',
            table='patients',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
